### ISSUE TITLE
Needs to be updated for Orchard 1.9

### ISSUE THREAD

**Issue by dcinzona** [bhavinbdoshi/Om.Orchard.SocialMetaTags#2]
Should be able to just change the framework to 4.5.1

**Comment by bhavinbdoshi** [comment]
The update for 4.5.1 is tested and works fine. I need to check in the branch for that. Will do that tonight.

**Comment by bhavinbdoshi** [comment]
Branch 1.1 is now updated for 4.5.1 for orchard 1.9
